version: '3.8'

services:
  app:
    image: sp
    ports:
      - "8080:8080"
    container_name: sp
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@db:27017/sp
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - db

volumes:
  db_data:
